title: Kyoto Sustainable -Vegan Map
description: Google スプレッドシートを更新するだけでオリジナルの地図アプリを作成できる\n「Geolonia PWAマップ」
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vS7QqBRcyoszR4hjwd7JfMyas0y3E2POrq35mneJa5fzfX6ZgchZrjKXxHFE0GoxRRW4TlMstgXlicB/pub?gid=1957425126&single=true&output=csv
form_url:
logo_image_url: https://geoloniamaps.github.io/pwamap/icon-pwamap.svg
background_image_url: https://geoloniamaps.github.io/pwamap/geolonia_bgimage_1920_1080.png
primary_color: "#d2691e"
orderby: distance
